<p>2018-12-10 10:00:12,559 — INFO: Start app</p>
<p>2018-12-10 10:00:12,559 — INFO: Request to files/download</p>
<p>2018-12-10 10:00:14,240 — INFO: Download project data base from dropbox server.</p>
<p>2018-12-10 10:00:14,249 — INFO: Request to files/list_folder</p>
<p>2018-12-10 10:00:14,309 — WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4861aeec18>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /bot700887235:AAEMUZmPSfF4gCzNs9O_nyU8-jCkDY2GgDY/deleteWebhook</p>
<p>2018-12-10 10:00:14,349 — WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4868554a58>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /bot700887235:AAEMUZmPSfF4gCzNs9O_nyU8-jCkDY2GgDY/deleteWebhook</p>
<p>2018-12-10 10:00:14,429 — WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4868554eb8>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /bot700887235:AAEMUZmPSfF4gCzNs9O_nyU8-jCkDY2GgDY/deleteWebhook</p>
<p>2018-12-10 10:00:14,487 — ERROR: Error while bootstrap del webhook: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot700887235:AAEMUZmPSfF4gCzNs9O_nyU8-jCkDY2GgDY/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4868554fd0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))</p>
<p>2018-12-10 10:00:14,488 — WARNING: Failed bootstrap phase; try=1 max_retries=-1</p>
<p>2018-12-10 10:00:16,162 — INFO: Request to files/download</p>
<p>2018-12-10 10:00:17,301 — INFO: Download project data base from dropbox server.</p>
<p>2018-12-10 10:00:17,302 — INFO: Request to files/upload</p>
<p>2018-12-10 10:00:18,485 — INFO: Upload project data base to dropbox server.</p>
<p>2018-12-10 10:00:22,129 — WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4861ab77b8>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /bot700887235:AAEMUZmPSfF4gCzNs9O_nyU8-jCkDY2GgDY/deleteWebhook</p>
<p>2018-12-10 10:00:22,177 — WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4868556ba8>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /bot700887235:AAEMUZmPSfF4gCzNs9O_nyU8-jCkDY2GgDY/deleteWebhook</p>
<p>2018-12-10 10:00:22,235 — WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4868556c18>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /bot700887235:AAEMUZmPSfF4gCzNs9O_nyU8-jCkDY2GgDY/deleteWebhook</p>
<p>2018-12-10 10:00:22,289 — ERROR: Error while bootstrap del webhook: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot700887235:AAEMUZmPSfF4gCzNs9O_nyU8-jCkDY2GgDY/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4868556978>: Failed to establish a new connection: [Errno 101] Network is unreachable',))</p>
<p>2018-12-10 10:00:22,289 — WARNING: Failed bootstrap phase; try=2 max_retries=-1</p>
<p>2018-12-10 10:00:33,671 — WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4868556940>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /bot700887235:AAEMUZmPSfF4gCzNs9O_nyU8-jCkDY2GgDY/deleteWebhook</p>
<p>2018-12-10 10:00:33,711 — WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f48685561d0>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /bot700887235:AAEMUZmPSfF4gCzNs9O_nyU8-jCkDY2GgDY/deleteWebhook</p>
<p>2018-12-10 10:00:33,771 — WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4861ab79b0>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /bot700887235:AAEMUZmPSfF4gCzNs9O_nyU8-jCkDY2GgDY/deleteWebhook</p>
<p>2018-12-10 10:00:33,831 — ERROR: Error while bootstrap del webhook: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot700887235:AAEMUZmPSfF4gCzNs9O_nyU8-jCkDY2GgDY/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4863e33048>: Failed to establish a new connection: [Errno 101] Network is unreachable',))</p>
<p>2018-12-10 10:00:33,831 — WARNING: Failed bootstrap phase; try=3 max_retries=-1</p>
<p>2018-12-10 10:00:50,812 — WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f48620f9e48>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /bot700887235:AAEMUZmPSfF4gCzNs9O_nyU8-jCkDY2GgDY/deleteWebhook</p>
<p>2018-12-10 10:00:50,846 — WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4862098438>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /bot700887235:AAEMUZmPSfF4gCzNs9O_nyU8-jCkDY2GgDY/deleteWebhook</p>
<p>2018-12-10 10:00:50,891 — WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f48620a6c88>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /bot700887235:AAEMUZmPSfF4gCzNs9O_nyU8-jCkDY2GgDY/deleteWebhook</p>
<p>2018-12-10 10:00:50,932 — ERROR: Error while bootstrap del webhook: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot700887235:AAEMUZmPSfF4gCzNs9O_nyU8-jCkDY2GgDY/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f48620bf860>: Failed to establish a new connection: [Errno 101] Network is unreachable',))</p>
<p>2018-12-10 10:00:50,933 — WARNING: Failed bootstrap phase; try=4 max_retries=-1</p>
<p>2018-12-10 10:01:16,415 — WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f48620f9eb8>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /bot700887235:AAEMUZmPSfF4gCzNs9O_nyU8-jCkDY2GgDY/deleteWebhook</p>
<p>2018-12-10 10:01:16,455 — WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f48625ac6d8>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /bot700887235:AAEMUZmPSfF4gCzNs9O_nyU8-jCkDY2GgDY/deleteWebhook</p>
<p>2018-12-10 10:01:16,514 — WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4862aedeb8>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /bot700887235:AAEMUZmPSfF4gCzNs9O_nyU8-jCkDY2GgDY/deleteWebhook</p>
<p>2018-12-10 10:01:16,574 — ERROR: Error while bootstrap del webhook: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot700887235:AAEMUZmPSfF4gCzNs9O_nyU8-jCkDY2GgDY/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f486208c8d0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))</p>
<p>2018-12-10 10:01:16,575 — WARNING: Failed bootstrap phase; try=5 max_retries=-1</p>
<p>2018-12-10 10:01:54,756 — WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f486205bb70>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /bot700887235:AAEMUZmPSfF4gCzNs9O_nyU8-jCkDY2GgDY/deleteWebhook</p>
<p>2018-12-10 10:01:54,797 — WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4862038550>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /bot700887235:AAEMUZmPSfF4gCzNs9O_nyU8-jCkDY2GgDY/deleteWebhook</p>
<p>2018-12-10 10:01:54,858 — WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4868554e80>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /bot700887235:AAEMUZmPSfF4gCzNs9O_nyU8-jCkDY2GgDY/deleteWebhook</p>
<p>2018-12-10 10:01:54,917 — ERROR: Error while bootstrap del webhook: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot700887235:AAEMUZmPSfF4gCzNs9O_nyU8-jCkDY2GgDY/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f48685549e8>: Failed to establish a new connection: [Errno 101] Network is unreachable',))</p>
<p>2018-12-10 10:01:54,917 — WARNING: Failed bootstrap phase; try=6 max_retries=-1</p>
<p>2018-12-10 10:02:25,028 — WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4868554a58>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /bot700887235:AAEMUZmPSfF4gCzNs9O_nyU8-jCkDY2GgDY/deleteWebhook</p>
<p>2018-12-10 10:02:25,059 — WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4861aeec50>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /bot700887235:AAEMUZmPSfF4gCzNs9O_nyU8-jCkDY2GgDY/deleteWebhook</p>
<p>2018-12-10 10:02:25,099 — WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4861aeeeb8>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /bot700887235:AAEMUZmPSfF4gCzNs9O_nyU8-jCkDY2GgDY/deleteWebhook</p>
<p>2018-12-10 10:02:25,139 — ERROR: Error while bootstrap del webhook: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot700887235:AAEMUZmPSfF4gCzNs9O_nyU8-jCkDY2GgDY/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4861aee550>: Failed to establish a new connection: [Errno 101] Network is unreachable',))</p>
<p>2018-12-10 10:02:25,140 — WARNING: Failed bootstrap phase; try=7 max_retries=-1</p>
<p>2018-12-10 10:02:55,421 — WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4861aeee10>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /bot700887235:AAEMUZmPSfF4gCzNs9O_nyU8-jCkDY2GgDY/deleteWebhook</p>
<p>2018-12-10 10:02:55,463 — WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4861aeefd0>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /bot700887235:AAEMUZmPSfF4gCzNs9O_nyU8-jCkDY2GgDY/deleteWebhook</p>
<p>2018-12-10 10:02:55,523 — WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f48587c50f0>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /bot700887235:AAEMUZmPSfF4gCzNs9O_nyU8-jCkDY2GgDY/deleteWebhook</p>
<p>2018-12-10 10:02:55,583 — ERROR: Error while bootstrap del webhook: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot700887235:AAEMUZmPSfF4gCzNs9O_nyU8-jCkDY2GgDY/deleteWebhook (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4861aee7b8>: Failed to establish a new connection: [Errno 101] Network is unreachable',))</p>
<p>2018-12-10 10:02:55,583 — WARNING: Failed bootstrap phase; try=8 max_retries=-1</p>
